name: CI

on:
  push:
    branches:
      - main
      - test
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run:  make test_container

  test-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run:  
          make test_container_manual || /usr/bin/true
